runtime: nodejs16 # or another supported version
env: standard

env_variables:
  SQL_USER: root
  SQL_PASSWORD: "root123@"
  SQL_DATABASE: bancoaustro
  INSTANCE_CONNECTION_NAME: bank3-332900:us-central1:nodejsmysql

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances:  bank3-332900:us-central1:nodejsmysql
